import ClientModel  from './client.js';
import CompanyModel  from './company.js';
import CreditModel  from './credit.js';
import EmployeeModel  from './employee.js';
import LocationModel  from './location.js';
import RouteModel  from './route.js';
import TransactionModel  from './transaction.js';
import UserModel  from './user.js';
import TripModel  from './trip.js';
import SupplierModel  from './supplier.js';
import ProductModel  from './product.js';
import PriceModel  from './price.js';
import ProductTransactionModel  from './productTransaction.js';

export const Client = ClientModel;
export const Company = CompanyModel;
export const Credit = CreditModel;
export const Employee = EmployeeModel;
export const Location = LocationModel;
export const Route = RouteModel;
export const Transaction = TransactionModel;
export const User = UserModel;
export const Trip = TripModel;
export const Supplier = SupplierModel;
export const Product = ProductModel;
export const Price = PriceModel;
export const ProductTransaction = ProductTransactionModel;